# Generated by Django 5.0.4 on 2024-05-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VENTAS', '0005_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
