# Generated by Django 5.0.4 on 2024-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENTAS', '0008_alter_pedido_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
