# Generated by Django 5.0.4 on 2024-05-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VENTAS', '0010_pedido_clientevalidator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='clienteValidator',
        ),
    ]
