# Generated by Django 5.0.4 on 2024-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Contraseña del Cliente'),
        ),
    ]
