# Generated by Django 5.0.4 on 2024-05-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_cliente_password'),
        ('RRHH', '0002_remove_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado', verbose_name='Comercial Asignado'),
        ),
    ]
