# Generated by Django 5.0.4 on 2024-05-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_cliente_comercial'),
        ('RRHH', '0002_remove_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoDocumento', models.CharField(choices=[('dni', 'DNI'), ('nif', 'NIF'), ('cif', 'CIF'), ('pasaporte', 'Pasaporte'), ('nie', 'NIE')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=60, verbose_name='Documento del Cliente')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña del Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('tipoCliente', models.CharField(blank=True, choices=[('particular', 'particular'), ('empresa', 'empresa')], max_length=200, verbose_name='Tipo de Cliente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('comercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado', verbose_name='Comercial Asignado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.cliente')),
            ],
        ),
    ]
