# Generated by Django 5.0.4 on 2024-05-28 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_clientevalidator'),
        ('RRHH', '0002_remove_empleado_user'),
        ('VENTAS', '0011_remove_pedido_clientevalidator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RRHH.empleado', verbose_name='Comercial Asignado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_registro', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='ClienteValidator',
        ),
    ]
